### ISSUE TITLE
"main" java.nio.file.InvalidPathException: Illegal char <:> at index 7: WARNING: (0) : No source files specified\bsp\data

### ISSUE THREAD

**Issue by lakshmanmallidi** [dirs-dev/directories-jvm#25]
I am using scala metals library in vscode. I got  error stating as below

`"main" java.nio.file.InvalidPathException: Illegal char <:> at index 7: WARNING: (0) : No source files specified\bsp\data`

In scala metals library we are following this issue in #1085 (https://github.com/scalameta/metals/issues/1085). We came to know the issue is with directories-jvm  as scala metals is using directories-jvm. 

Below code gives us an info about ProjectDirectories configured

` System.out.println(ProjectDirectories.fromPath("bsp"));`

Output:

`ProjectDirectories (Windows 10):
projectPath = 'bsp'
cacheDir = '\bsp\cache'
configDir = 'WARNING: (0) : No source files specified\bsp\config'
dataDir = 'WARNING: (0) : No source files specified\bsp\data'
dataLocalDir = '\bsp\data'
runtimeDir = 'null'`

I understand that in `configDir` path a warning message is append to the path which causing the error. But i don't have any idea what it is happening, can please check on this issue.

**Comment by soc** [comment]
Hi @lakshmanmallidi, I have started to look into this yesterday – would it be possible for you to run the underlying powershell command on a machine suffering from this issue directly?

This would allow locating the exact layer at which this error occurs.

E.g. open powershell and run: 
```
Add-Type @"
using System;
using System.Runtime.InteropServices;
public class Dir {
   [DllImport("shell32.dll")]
   private static extern int SHGetKnownFolderPath([MarshalAs(UnmanagedType.LPStruct)] Guid rfid, uint dwFlags, IntPtr hToken, out IntPtr pszPath);
   public static string GetKnownFolderPath(string rfid) {
       IntPtr pszPath;
       if (SHGetKnownFolderPath(new Guid(rfid), 0, IntPtr.Zero, out pszPath) != 0) return "";
       string path = Marshal.PtrToStringUni(pszPath);
       Marshal.FreeCoTaskMem(pszPath);
       return path;
   }
}
"@
[Dir]::GetKnownFolderPath("5E6C858F-0E22-4760-9AFE-EA3317B67173")
[Dir]::GetKnownFolderPath("3EB685DB-65F9-4CF6-A03A-E3EF65729F3D")
[Dir]::GetKnownFolderPath("F1B32785-6FBA-4FCF-9D55-7B8E7F157091")
```

After that, could you run the command again with `-IgnoreWarnings` added between `Add-Type` and `@"`? (The command should start like this now: `Add-Type -IgnoreWarnings @"`.)

I think this is some issue that warnings gets emitted on the console while running the command, from which we try to parse the path results.

Thanks!

**Comment by lakshmanmallidi** [comment]
I am getting below log or error when executing above code in my powershell.

```
Add-Type : (0) : Source file 'C:\windows\TEMP\krdidrxl.0.cs' could not be found
(1) : using System;
At line:1 char:1
+ Add-Type -IgnoreWarnings @"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Except
   ion
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand

WARNING: (0) : No source files specified

(1) : using System;
Add-Type : Cannot add type. Compilation errors occurred.
At line:1 char:1
+ Add-Type -IgnoreWarnings @"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
    + FullyQualifiedErrorId : COMPILER_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand
```

**Comment by soc** [comment]
Is `C:\windows\TEMP\krdidrxl.0.cs` a file you created? If not, does the filename change when you run the script again?

**Comment by lakshmanmallidi** [comment]
I don't created that file and if i run the script again file is changed. 
```
 $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  771
```

**Comment by soc** [comment]
Ok, thanks!

Are there any group policies, virus scanners or other permission restrictions that could interfere with the creation of this file?

Sounds pretty much like `Add-Type` emits a *.cs file for the C# portion of the code, and it fails because it can't place the file were it expects.

**Comment by DamianReeves** [comment]
I believe this and other powershell related issues in this repo is related to the fact powershell is invoked without passing the `-noprofile` flag. Powershell should be invoked with the `-noprofile` flag otherwise the user's profile may interfere with the expected results of the script that is being ran.

**Comment by soc** [comment]
I think this is fixed, as we use `-noprofile` now – please reopen, if this is still an issue!
