### ISSUE TITLE
Release new version with recent updates?

### ISSUE THREAD

**Issue by tgodzik** [dirs-dev/directories-jvm#31]
Hi! Thanks for the great work on the library!

I noticed that there are recent fixes that might benefit some users of our project (Metals). I was wondering if it's possible to make a new release with those recent changes? I there is anything blocking maybe we can help out? Thanks!

The related issue in Metals: https://github.com/scalameta/metals-vscode/issues/208

**Comment by soc** [comment]
Hi Tomasz,

I'm currently waiting for a response in https://github.com/soc/directories-jvm/pull/30, I planned to ship a new version after resolving that issue.

I'll ping people again.

Thanks,

Simon

**Comment by tgodzik** [comment]
Thanks!

**Comment by alexarchambault** [comment]
FYI, I [just switched](https://github.com/coursier/coursier/pull/1667) to the current master of directories-jvm in coursier, as it's a source dependency there, it seems to work fine.

**Comment by soc** [comment]
Great, thanks for the heads up!

**Comment by soc** [comment]
Heads up: I just published v12.

**Comment by soc** [comment]
@alexarchambault Do you have any idea what's happening on the CI?

```
[error] [launcher] download failed: org.scala-lang.modules#scala-xml_2.12;1.2.0!scala-xml_2.12.jar(bundle)
```

Link: https://ci.appveyor.com/project/soc/directories-jvm/branch/master
