### ISSUE TITLE
getWinDirs should invoke powershell with the -Noprofile flag

### ISSUE THREAD

**Issue by DamianReeves** [dirs-dev/directories-jvm#36]
I have had trouble on a windows machine using coursier, metals, and other tools which have a transitive dependency on directories-jvm. After doing some tracing, I was able to discover that the issue is that `directories-jvm` invokes powershell for windows without the `-noprofile` flag. 

Pulling the code down locally and simply adding the `-Noprofile` flag fixed the path resolutions which previously failed for me.

```java
  static String[] getWinDirs(String... guids) {

    int guidsLength = guids.length;
    StringBuilder buf = new StringBuilder(guidsLength * 68);
    for (int i = 0; i < guidsLength; i++) {
      buf.append("[Dir]::GetKnownFolderPath(\"");
      buf.append(guids[i]);
      buf.append("\")\n");
    }

    String encodedCommand = SCRIPT_START_BASE64 + toUTF16LEBase64(buf.toString() + "}");

    return runCommands(guidsLength, Charset.forName("UTF-8"),
        "powershell.exe",
        "-Noprofile",
        "-EncodedCommand",
        encodedCommand
    );
  }
```

**Comment by alexarchambault** [comment]
@soc I agree with @DamianReeves that `-NoProfile` should be passed to `powershell.exe`. I've been using it fine [here](https://github.com/alexarchambault/windows-ansi/blob/c303b8f22165b5491f437f4a719be26cb3589052/ps/src/main/java/io/github/alexarchambault/windowsansi/PowershellRunner.java#L20). This code runs along directories-jvm in coursier's bootstraps, no one has complained about it.

FWIW, [this project](https://github.com/profesorfalken/jPowerShell/blob/c26cbf10c36c5ab7561492d9620680ed8122d3bc/src/main/java/com/profesorfalken/jpowershell/PowerShell.java#L143) passes `-NoProfile` too.

**Comment by soc** [comment]
Any other args we should also use?

**Comment by alexarchambault** [comment]
[`-NonInteractive`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe?view=powershell-5.1#-noninteractive) can't hurt, I guess. I've been using it fine in [windows-ansi](https://github.com/alexarchambault/windows-ansi/blob/c303b8f22165b5491f437f4a719be26cb3589052/ps/src/main/java/io/github/alexarchambault/windowsansi/PowershellRunner.java#L21) too.

Don't know about `-ExecutionPolicy bypass` used by [jpowershell](https://github.com/profesorfalken/jPowerShell/blob/c26cbf10c36c5ab7561492d9620680ed8122d3bc/src/main/java/com/profesorfalken/jpowershell/PowerShell.java#L143)…

**Comment by alexarchambault** [comment]
Wondering if `-ExecutionPolicy bypass` would address https://github.com/scalameta/metals/issues/1932…
