### ISSUE TITLE
UTF-8 BOM prefix should be stripped from ProjectDirectories.configDir

### ISSUE THREAD

**Issue by tgodzik** [dirs-dev/directories-jvm#37]
It looks like on Windows (though not reproducible on every machine) `configDir` comes with an UTF-8 BOM prefix.

It was suggested by @alexarchambault that we should strip it automatically similar to https://github.com/coursier/coursier/commit/fac264f7b78c945f72b06f2fcad9725afd861510

The full discussion is here https://github.com/scalameta/metals/issues/1925

Should we just do that in this case?

**Comment by soc** [comment]
Although I'd argue that Microsoft needs to fix their software, yes probably. :-)
