### ISSUE TITLE
Add fallback path if powershell command fails.

### ISSUE THREAD

**Issue by xxDark** [dirs-dev/directories-jvm#42]
See https://github.com/Col-E/Recaf/issues/278 for more info.

**Comment by soc** [comment]
From where would we get the fallback path?

**Comment by xxDark** [comment]
Grab the directories from env. variables I guess.
Such as: `APPDATA`, `USERPROFILE`, `LOCALAPPDATA`

**Comment by soc** [comment]
I don't think the environment variables are wired up to the `SHGetKnownFolderPath`, so using them would mean we would be potentially out of sync with what actual applications see.

**Comment by soc** [comment]
I have released versions 22 and 23 which hopefully address this issue.

Version 22 make the library not throw an exception if there is an issue, and version 23 tries to be a bit sneakier trying to retrieve the values. Use 23, but if there are issues with the approach you can fall back to 22.
