### ISSUE TITLE
Util.getWinDirs throws an exception if PowerShell is in Constrained Language Mode

### ISSUE THREAD

**Issue by fthomas** [dirs-dev/directories-jvm#43]
If PowerShell is in [Constrained Language Mode](https://devblogs.microsoft.com/powershell/powershell-constrained-language-mode/), that is `PS C:\> $ExecutionContext.SessionState.LanguageMode` prints `ConstrainedLanguage` instead of `FullLanguage`, `Util.getWinDirs` throws an exception which can be observed by running `dev.dirs.DirectoriesTest`:
```
sbt:directories> testOnly dev.dirs.DirectoriesTest
[info] Total time: 0 sec
[info] Compiling 1 Java source to C:\Project\prj\directories-jvm\target\test-classes ...
[error] Test dev.dirs.DirectoriesTest.testBaseDirectories failed: java.lang.RuntimeException: Couldn't find pwsh.exe or powershell.exe on path or in default system locations, took 2.545 sec
[error]     at dev.dirs.Util.windowsFallback(Util.java:280)
[error]     at dev.dirs.Util.getWinDirs(Util.java:161)
[error]     at dev.dirs.BaseDirectories.<init>(BaseDirectories.java:274)
[error]     at dev.dirs.BaseDirectories.get(BaseDirectories.java:246)
[error]     at dev.dirs.DirectoriesTest.testBaseDirectories(DirectoriesTest.java:9)
[error]     ...
[error] Caused by: java.io.IOException: no output from process
[error]     at dev.dirs.Util.runCommands(Util.java:206)
[error]     at dev.dirs.Util.runWinCommands(Util.java:241)
[error]     at dev.dirs.Util.windowsFallback(Util.java:278)
[error]     ... 41 more
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error]         dev.dirs.DirectoriesTest
[info] Total time: 3 sec
[info]   root / Test / testOnly: 3 sec
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 3 s, completed 19.11.2020 14:08:57
```
The inner exception `java.io.IOException: no output from process` is thrown because the PowerShell process exits with only printing to stderr and nothing to stdout.

PowerShell exits with errors when trying to execute the [SCRIPT_START_BASE64](https://github.com/dirs-dev/directories-jvm/blob/fcb1a8ce3c318352164236f6371c5b4d44af46e7/src/main/java/dev/dirs/Util.java#L49-L65) script. The error can be reproduced in a PowerShell console by executing the first line of that script:
```powershell
PS C:\> $ExecutionContext.SessionState.LanguageMode
FullLanguage
PS C:\> [Console]::OutputEncoding = [System.Text.Encoding]::UTF8

PS C:\> $ExecutionContext.SessionState.LanguageMode = "ConstrainedLanguage"

PS C:\> $ExecutionContext.SessionState.LanguageMode
ConstrainedLanguage
PS C:\> [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
Die Eigenschaft kann nicht festgelegt werden. Das Festlegen der Eigenschaft wird in diesem Sprachmodus nur für Kerntypen unterstützt.
In Zeile:1 Zeichen:1
+ [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertySetterNotSupportedInConstrainedLanguage
```
Note that `[Console]::OutputEncoding = [System.Text.Encoding]::UTF8` does not exit with an error in `FullLanguage` mode.

That `Util.getWinDirs` throws an exception if PowerShell is in Constrained Language Mode is the reason why the current sbt 1.4 versions are not usable in such environments as noted in https://github.com/dirs-dev/directories-jvm/pull/40#issuecomment-729581072 and https://github.com/coursier/coursier/issues/1913.

A possible workaround to make sbt usable again would be removing [this line](https://github.com/dirs-dev/directories-jvm/commit/74a100907f4e40fee5368425b0c232f4da494f2e#diff-e1beb805598d360f4a22dfef3fa4d511d45711c8f744d93148e0e44d03ff869bR201).

**Comment by soc** [comment]
> A possible workaround to make sbt usable again would be removing this line.

I'm not sure returning silently `null` for everything is the right fix.

**Comment by soc** [comment]
@fthomas Could you try whether running `powershell -version 2`¹ changes things?

¹ https://www.ired.team/offensive-security/code-execution/powershell-constrained-language-mode-bypass

**Comment by fthomas** [comment]
Yes, it does:
```powershell
PS C:\> $ExecutionContext.SessionState.LanguageMode
ConstrainedLanguage
PS C:\> powershell -version 2
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

PS C:\> $ExecutionContext.SessionState.LanguageMode
FullLanguage
```
The tests also pass with the following change:
```diff
diff --git a/src/main/java/dev/dirs/Util.java b/src/main/java/dev/dirs/Util.java
index 679bb67..bd1ef6b 100644
--- a/src/main/java/dev/dirs/Util.java
+++ b/src/main/java/dev/dirs/Util.java
@@ -225,6 +225,8 @@ final class Util {
           try {
             return runCommands(guidsLength, Charset.forName("UTF-8"),
                 commandFile.toString(),
+                "-version",
+                "2",
                 "-NoProfile",
                 "-EncodedCommand",
                 encodedCommand
```

**Comment by fthomas** [comment]
> I'm not sure returning silently `null` for everything is the right fix.

I agree. But this has been the behaviour for users whose PowerShell is in `ConstrainedLanguage` before #40 was merged and it would make sbt usable again. Another alternative would be to use env variables as fallback if PowerShell fails (https://github.com/dirs-dev/directories-jvm/issues/42#issuecomment-692904522).

**Comment by eed3si9n** [comment]
There's some discussion about environment variables in this thread - https://github.com/dirs-dev/directories-jvm/issues/26#issuecomment-570288952

In my opinion, the majority of the sbt users would be happy as long as directories-jvm reliably returned _any_ value, and it doesn't really have to be Apple/Microsoft/freedesktop compliant. I mean it would be _nice_ if the value was correct in some sense, but for the sake of downloading JARs in some CI box on Windows etc, erroring out because Powershell or whatever is many times worse outcome than directories-jvm falling back to some stable made-up value.

For that I think we should consider the 3-step strategy:
1. On Windows, try environment variable first. If it's there, no need to deal with powershell. Great.
2. If the environmental variable is missing, only then try powershell, catch any errors, and print them out in the stderr.
3. If powershell bailed, use some hard-coded reasonable fallback.

**Comment by kalejami** [comment]
Opened a PR #45 for using System.env before using powershell. The used GUIDs are hardcoded. Don't know if this is good enough or we should find a more generic way to do this. For many GUIDS there a no System.envs so I have to concat strings to get them. If any of the concated strings change in future WinOS versions it will break. Don't know how to prevent this

**Comment by soc** [comment]
@eed3si9n The problem with environment variables on Windows is that the conventions and expectations around it are completely different then on Linux, where we use environment variables for exactly this case. (Which is the reason why they were intentionally not used from the beginning of the dirs project.)

Changing the environment variables has meaning on Linux, and changing them has an effect, as other applications use them as a source of truth.

On Windows on the other hand, I'm pretty sure that pretty much nothing will ever check environment variables and I'm pretty sure that changing them has no effect on what the `SHGetKnownFolderPath` function returns, which is what 99.9% of everyone is using.

So what would be great would be setting the environment variables and then checking if the API returns the new values too, if no, I don't think that would be the way to go.

**Comment by eed3si9n** [comment]
> On Windows on the other hand, I'm pretty sure that pretty much nothing will ever check environment variables and I'm pretty sure that changing them has no effect on what the `SHGetKnownFolderPath` function returns, which is what 99.9% of everyone is using.

I feel like we're talking past each other, and maybe I'm not seeing some use case in mind. I'm not suggesting that the user should set `APPDATA` or `LOCALAPPDATA` environment variable, or how other Windows applications should change their behavior. All I'm saying is that when one of environment variables is available, and it often is, we should try that first. These environment variables are documented even in [KNOWNFOLDERID](https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid) reference to define the default paths.

**Comment by soc** [comment]
The problem is that when users set these environment variables, does `SHGetKnownFolderPath` act in sync with these changes?
This would be the most important thing to find out.

**Comment by fthomas** [comment]
> The problem is that when users set these environment variables, does SHGetKnownFolderPath act in sync with these changes?

It doesn't look like it. I tried several variations of 
```powershell
PS C:\> $env:LOCALAPPDATA = 'C:\foo'
PS C:\> [Environment]::GetFolderPath('LocalApplicationData')
C:\Users\***\AppData\Local
```
in the PowerShell and none of the environment variables I tried changed the return value of `GetFolderPath`. This [C# API doc for `GetFolderPath`](https://docs.microsoft.com/en-us/dotnet/api/system.environment.getfolderpath?view=net-5.0) also doesn't mention that its output could be changed by setting environment variables and this (old) [StackOverflow question](https://stackoverflow.com/questions/4726818/expand-environment-variable-for-my-documents) also hints at that environment variables do not influence `GetFolderPath`.

@soc Any suggestions how we can move forward here? Would #46 be an acceptable workaround until a proper fix is implemented?

**Comment by soc** [comment]
@fthomas Yes, my plan is to use both #46 and the powershell version downgrade.
I'll ship a new release soon.

**Comment by soc** [comment]
@fthomas Thanks a lot trying out env vars vs. API, that was really a great help!

**Comment by soc** [comment]
I have released versions 22 and 23 which hopefully address this issue.

Version 22 make the library not throw an exception if there is an issue, and version 23 tries to be a bit sneakier trying to retrieve the values. Use 23, but if there are issues with the approach you can fall back to 22, while we have a new look at the problem.

**Comment by fthomas** [comment]
Many thanks for the releases, @soc. I opened https://github.com/coursier/coursier/pull/1938 to get the fix into Coursier and then sbt.

**Comment by fthomas** [comment]
FTR: sbt 1.4.6 is now using directories-jvm 23 via lm-coursier 2.0.5 / Coursier 2.0.8 and the fix with dowgrading the PowerShell version (https://github.com/dirs-dev/directories-jvm/commit/f976091da250fe3a85ca48df6041cf9852f79a09) seems to be working:
```
PS C:\> $ExecutionContext.SessionState.LanguageMode
ConstrainedLanguage
PS C:\> sbt csrCacheDirectory
...
[info] csrCacheDirectory
[info]  C:\Users\...\AppData\Local\Coursier\cache\v1
```
I can finally enjoy sbt 1.4 on Windows. Thanks @soc, @kalejami, @eed3si9n and @alexarchambault for fixing this issue and getting it into sbt!
