### ISSUE TITLE
Invalid path with leading 'null' on Windows 10

### ISSUE THREAD

**Issue by snlykf** [dirs-dev/directories-jvm#47]
Latest version 23 creates invalid paths with leading `null\` on Window 10.

I encountered this when updating SBT / coursier and dependencies where downloaded to a `null` dir inside my project.

### Actual

```scala
import dev.dirs.ProjectDirectories
import $dep.`dev.dirs:directories:23`

ProjectDirectories.from("org", "scalameta", "metals")
// res0: ProjectDirectories = ProjectDirectories (Windows 10):
//   projectPath   = 'scalameta\metals'
//   cacheDir      = 'null\scalameta\metals\cache'
//   configDir     = 'null\scalameta\metals\config'
//   dataDir       = 'null\scalameta\metals\data'
//   dataLocalDir  = 'null\scalameta\metals\data'
//   preferenceDir = 'null\scalameta\metals\config'
//   runtimeDir    = 'null'
```

### Expected
```scala
import dev.dirs.ProjectDirectories
import $dep.`dev.dirs:directories:22`

ProjectDirectories.from("org", "scalameta", "metals")
// res0: ProjectDirectories = ProjectDirectories (Windows 10):
//   projectPath   = 'scalameta\metals'
//   cacheDir      = 'C:\Users\user\AppData\Local\scalameta\metals\cache'
//   configDir     = 'C:\Users\user\AppData\Roaming\scalameta\metals\config'
//   dataDir       = 'C:\Users\user\AppData\Roaming\scalameta\metals\data'
//   dataLocalDir  = 'C:\Users\user\AppData\Local\scalameta\metals\data'
//   preferenceDir = 'C:\Users\user\AppData\Roaming\scalameta\metals\config'
//   runtimeDir    = 'null'
```

### Environment
**OS:** Windows 10 1903
**JVM:** AdoptOpenJDK 1.8.0_222 / 1.8.0_282

**Comment by soc** [comment]
Thanks, I will look into this.

**Comment by snlykf** [comment]
Maybe duplicate of / related to https://github.com/dirs-dev/directories-jvm/issues/26

Looked at the differences between 22 and 23 (https://github.com/dirs-dev/directories-jvm/commit/f976091da250fe3a85ca48df6041cf9852f79a09): Only changes is that PowerShell is always(?) downgraded with `-version 2` parameter. However, this fails on my machine:

```bash
PS C:\Users\snlykf> powershell -version 2
Problem beim Lesen der Registrierung. Der Registrierungsschlüssel "SOFTWARE\Microsoft\PowerShell\1\PowerShellEngine" wurde nicht gefunden. Das Windows PowerShell-Modul "2" ist auf diesem Computer nicht installiert.
```
> Problem reading registry. The registry key "SOFTWARE \ Microsoft \ PowerShell \ 1 \ PowerShellEngine" was not found. Windows PowerShell module "2" is not installed on this computer.

However, it should not need to downgrade as the shell is not constrained:
```
PS C:\Users\snlykf> $ExecutionContext.SessionState.LanguageMode
FullLanguage

PS C:\Users\snleyk> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by soc** [comment]
@fthomas Do you think it would make sense to check for the error message here and try without `-version 2`, or go a different route?

**Comment by fthomas** [comment]
Trying without `-version 2` if Powershell fails sounds sensible to me but I would probably not check the error message because it is localized.

Btw, has somebody tried using [JNA](https://github.com/java-native-access/jna/blob/d033fb429fb2b990ef2fde21772b1dee5b0d91ee/contrib/platform/src/com/sun/jna/platform/win32/Shell32.java#L143) instead of shelling out to Powershell. Maybe that is easier than fighting Powershell.

**Comment by soc** [comment]
Yes, was discussed in https://github.com/dirs-dev/directories-jvm/issues/16.

**Comment by soc** [comment]
@fthomas Would you be willing to have a look and see if you can adjust the code to try it both with and without `-version 2`?

**Comment by fthomas** [comment]
I can't make any commitments right now, I'm already swamped with other work.

But I'd be also OK with reverting f976091da250fe3a85ca48df6041cf9852f79a09 (which should fix this issue) since 4e5488c74fe39a2262ea22802e164d4c69d82217 was already enough to fix #43.

**Comment by soc** [comment]
Ok, thank you!

**Comment by phongngtuan** [comment]
Hi, may I give this a try?

**Comment by soc** [comment]
@phongngtuan Thanks for the offer! I think I'd first try reverting f976091 as @fthomas mentioned – though it might also be interesting to try extracting the info both with and without `-version 2` as mentioned above.

> Should we take what we can get if the fallback fails or should it fail loudly and throw exception back up?

I think that was the complaint that was addressed in 4e5488c?

**Comment by nartamonov** [comment]
It seems that all recent versions of SBT since 1.4.6 are vulnerable to the bug, see sbt/sbt#5206. 

Reverting f976091 resolves this issue on my computer with Windows 10.

**Comment by soc** [comment]
Could you check whether version 24 fixes this?

**Comment by snlykf** [comment]
24 fixes it for me:


```scala
import dev.dirs.ProjectDirectories
import $dep.`dev.dirs:directories:24`

ProjectDirectories.from("org", "scalameta", "metals")
// res0: ProjectDirectories = ProjectDirectories (Windows 10):
//   projectPath   = 'scalameta\metals'
//   cacheDir      = 'C:\Users\snlykf\AppData\Local\scalameta\metals\cache'
//   configDir     = 'C:\Users\snlykf\AppData\Roaming\scalameta\metals\config'
//   dataDir       = 'C:\Users\snlykf\AppData\Roaming\scalameta\metals\data'
//   dataLocalDir  = 'C:\Users\snlykf\AppData\Local\scalameta\metals\data'
//   preferenceDir = 'C:\Users\snlykf\AppData\Roaming\scalameta\metals\config'
//   runtimeDir    = 'null'
```

**Comment by nartamonov** [comment]
> Could you check whether version 24 fixes this?

24 works for me:

```shell
scala> import dev.dirs.ProjectDirectories
import dev.dirs.ProjectDirectories

scala> ProjectDirectories.from("org", "scalameta", "metals")
res0: dev.dirs.ProjectDirectories =
ProjectDirectories (Windows 10):
  projectPath   = 'scalameta\metals'
  cacheDir      = 'C:\Users\narta\AppData\Local\scalameta\metals\cache'
  configDir     = 'C:\Users\narta\AppData\Roaming\scalameta\metals\config'
  dataDir       = 'C:\Users\narta\AppData\Roaming\scalameta\metals\data'
  dataLocalDir  = 'C:\Users\narta\AppData\Local\scalameta\metals\data'
  preferenceDir = 'C:\Users\narta\AppData\Roaming\scalameta\metals\config'
  runtimeDir    = 'null'
```

**Comment by soc** [comment]
Thanks @snlykf and @nartamonov for checking, and thanks to @phongngtuan for fixing it!

Closing this, let me know if you experience this again!
