### ISSUE TITLE
.NET version?

### ISSUE THREAD

**Issue by zkat** [dirs-dev/directories-jvm#52]
Hi! I just finished an initial port of this library to .NET. I would like to donate it (and offer continued maintenance) to the dirs-dev org. Is that something you might be interested in?

**Comment by zkat** [comment]
Thanks! Sorry for the delay. Everything is pushed to `directories-net` now, and I've published it under my nuget account as `Directories.Net`. Please let me know if you'd like me to transfer control of the package to some other account :)

**Comment by soc** [comment]
No worries, @zkat! I had a hand OP, so I currently can't move the hand too much, but I'll review the code and think about a proper nuget account as soon as possible. Thanks!
